# Generated by Django 6.0.6 on 2026-06-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_cinema_approval_status_cinema_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
