server {
    listen 80;
    server_name your_domain.com www.your_domain.com;

    # Expose React frontend static folder
    location / {
        root /var/www/bookmymovie/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy api & admin requests to Gunicorn socket
    location /api/ {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location /admin/ {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    # Expose Django backend static assets
    location /static/ {
        alias /var/www/bookmymovie/backend/staticfiles/;
    }

    # Expose Django backend media assets
    location /media/ {
        alias /var/www/bookmymovie/backend/media/;
    }
}
